insert into ciudades(id, ciudad) values (1,"Alabama (AL)");
insert into ciudades(id, ciudad) values (2,"Alaska (AK)");
insert into ciudades(id, ciudad) values (3,"Arizona (AZ)");
insert into ciudades(id, ciudad) values (4,"Arkansas (AR)");
insert into ciudades(id, ciudad) values (5,"California (CA)");
insert into ciudades(id, ciudad) values (6,"Carolina del Norte (NC)");
insert into ciudades(id, ciudad) values (7,"Carolina del Sur (SC)");
insert into ciudades(id, ciudad) values (8,"Colorado (CO)");
insert into ciudades(id, ciudad) values (9,"Connecticut (CT)");
insert into ciudades(id, ciudad) values (10,"Dakota del Norte (ND)");
insert into ciudades(id, ciudad) values (11,"Dakota del Sur (SD)");
insert into ciudades(id, ciudad) values (12,"Delaware (DE)");
insert into ciudades(id, ciudad) values (13,"Florida (FL)");
insert into ciudades(id, ciudad) values (14,"Georgia (GA)");
insert into ciudades(id, ciudad) values (15,"Hawái (HI)");
insert into ciudades(id, ciudad) values (16,"Idaho (ID)");
insert into ciudades(id, ciudad) values (17,"Illinois (IL)");
insert into ciudades(id, ciudad) values (18,"Indiana (IN)");
insert into ciudades(id, ciudad) values (19,"Iowa (IA)");
insert into ciudades(id, ciudad) values (20,"Kansas (KS)");
insert into ciudades(id, ciudad) values (21,"Kentucky (KY)");
insert into ciudades(id, ciudad) values (22,"Luisiana (LA)");
insert into ciudades(id, ciudad) values (23,"Maine (ME)");
insert into ciudades(id, ciudad) values (24,"Maryland (MD)");
insert into ciudades(id, ciudad) values (25,"Massachusetts (MA)");
insert into ciudades(id, ciudad) values (26,"Míchigan (MI)");
insert into ciudades(id, ciudad) values (27,"Minnesota (MN)");
insert into ciudades(id, ciudad) values (28,"Misisipi (MS)");
insert into ciudades(id, ciudad) values (29,"Misuri (MO)");
insert into ciudades(id, ciudad) values (30,"Montana (MT)");
insert into ciudades(id, ciudad) values (31,"Nebraska (NE)");
insert into ciudades(id, ciudad) values (32,"Nevada (NV)");
insert into ciudades(id, ciudad) values (33,"Nueva Jersey (NJ)");
insert into ciudades(id, ciudad) values (34,"Nueva York (NY)");
insert into ciudades(id, ciudad) values (35,"Nuevo Hampshire (NH)");
insert into ciudades(id, ciudad) values (36,"Nuevo México (NM)");
insert into ciudades(id, ciudad) values (37,"Ohio (OH)");
insert into ciudades(id, ciudad) values (38,"Oklahoma (OK)");
insert into ciudades(id, ciudad) values (39,"Oregón (OR)");
insert into ciudades(id, ciudad) values (40,"Pensilvania (PA)");
insert into ciudades(id, ciudad) values (41,"Rhode Island (RI)");
insert into ciudades(id, ciudad) values (42,"Tennessee (TN)");
insert into ciudades(id, ciudad) values (43,"Texas (TX)");
insert into ciudades(id, ciudad) values (44,"Utah (UT)");
insert into ciudades(id, ciudad) values (45,"Vermont (VT)");
insert into ciudades(id, ciudad) values (46,"Virginia (VA)");
insert into ciudades(id, ciudad) values (47,"Virginia Occidental (WV)");
insert into ciudades(id, ciudad) values (48,"Washington (WA)");
insert into ciudades(id, ciudad) values (49,"Wisconsin (WI)");
insert into ciudades(id, ciudad) values (50,"Wyoming (WY)");
